-- Task Manager application schema for Supabase project mvxkssrpxaldmiknozoz.
-- Supabase is used as PostgreSQL storage only. Application authentication,
-- password reset tokens and transactional email remain managed by FastAPI/Brevo.

create table if not exists public.users (
    id integer generated by default as identity primary key,
    username varchar not null unique,
    email varchar not null unique,
    hashed_password varchar not null,
    first_name varchar(100),
    last_name varchar(100),
    is_active boolean not null default true,
    auth_version integer not null default 0,
    created_at timestamp without time zone not null default (now() at time zone 'utc')
);

create index if not exists ix_users_username on public.users (username);
create index if not exists ix_users_email on public.users (email);

create table if not exists public.tasks (
    id integer generated by default as identity primary key,
    title varchar not null,
    description text,
    completed boolean not null default false,
    status varchar not null default 'Not Started',
    priority varchar not null default 'Medium',
    due_date timestamp without time zone,
    tags varchar not null default '[]',
    time_estimate integer not null default 0,
    time_spent integer not null default 0,
    created_at timestamp without time zone not null default (now() at time zone 'utc'),
    updated_at timestamp without time zone not null default (now() at time zone 'utc'),
    owner_id integer not null references public.users(id) on delete cascade
);
create index if not exists ix_tasks_owner_id on public.tasks (owner_id);

create table if not exists public.contact_messages (
    id integer generated by default as identity primary key,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(255) not null,
    phone varchar(20) not null,
    message text not null,
    is_read boolean not null default false,
    created_at timestamp without time zone not null default (now() at time zone 'utc'),
    updated_at timestamp without time zone not null default (now() at time zone 'utc')
);

create table if not exists public.user_profiles (
    id integer generated by default as identity primary key,
    user_id integer not null unique references public.users(id) on delete cascade,
    phone varchar(20),
    address varchar(255),
    city varchar(100),
    state varchar(100),
    zip_code varchar(20),
    country varchar(100),
    gender varchar(50),
    date_of_birth timestamp without time zone,
    occupation varchar(150),
    company varchar(150),
    bio text,
    profile_picture text,
    created_at timestamp without time zone not null default (now() at time zone 'utc'),
    updated_at timestamp without time zone not null default (now() at time zone 'utc')
);

create table if not exists public.challenges (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    title varchar(200) not null,
    description text,
    duration integer not null,
    challenge_type varchar(50) not null,
    start_date timestamp without time zone not null,
    current_streak integer not null default 0,
    best_streak integer not null default 0,
    last_check_in timestamp without time zone,
    completed boolean not null default false,
    xp_reward integer not null default 0,
    icon varchar(100) not null default 'fas fa-bullseye',
    progress double precision not null default 0.0,
    is_active boolean not null default true,
    created_at timestamp without time zone not null default (now() at time zone 'utc'),
    updated_at timestamp without time zone not null default (now() at time zone 'utc')
);
create index if not exists ix_challenges_user_id on public.challenges (user_id);

create table if not exists public.habits (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    name varchar(200) not null,
    description text,
    category varchar(100),
    frequency varchar(50) not null default 'daily',
    target_count integer not null default 1,
    icon varchar(100),
    color varchar(50),
    created_at timestamp without time zone not null default (now() at time zone 'utc')
);
create index if not exists ix_habits_user_id on public.habits (user_id);

create table if not exists public.habit_entries (
    id integer generated by default as identity primary key,
    habit_id integer not null references public.habits(id) on delete cascade,
    user_id integer not null references public.users(id) on delete cascade,
    date timestamp without time zone not null,
    completed boolean not null default false,
    count integer not null default 1,
    mood integer,
    energy integer,
    notes text,
    created_at timestamp without time zone not null default (now() at time zone 'utc')
);
create index if not exists ix_habit_entries_habit_id on public.habit_entries (habit_id);
create index if not exists ix_habit_entries_user_id on public.habit_entries (user_id);

create table if not exists public.ai_conversations (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    question text not null,
    answer text not null,
    context json,
    feedback integer,
    created_at timestamp without time zone not null default (now() at time zone 'utc')
);
create index if not exists ix_ai_conversations_user_id on public.ai_conversations (user_id);

create table if not exists public.password_reset_tokens (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    token_hash varchar(64) not null unique,
    expires_at timestamp without time zone not null,
    used_at timestamp without time zone,
    created_at timestamp without time zone not null default (now() at time zone 'utc')
);
create index if not exists ix_password_reset_tokens_user_id on public.password_reset_tokens (user_id);
create index if not exists ix_password_reset_tokens_token_hash on public.password_reset_tokens (token_hash);

-- The frontend never talks to these tables through the Supabase Data API.
-- RLS with no client policies blocks anon/authenticated access while the backend's
-- direct Postgres connection continues to use the database role configured by the server.
alter table public.users enable row level security;
alter table public.tasks enable row level security;
alter table public.contact_messages enable row level security;
alter table public.user_profiles enable row level security;
alter table public.challenges enable row level security;
alter table public.habits enable row level security;
alter table public.habit_entries enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.password_reset_tokens enable row level security;

revoke all on table public.users from anon, authenticated;
revoke all on table public.tasks from anon, authenticated;
revoke all on table public.contact_messages from anon, authenticated;
revoke all on table public.user_profiles from anon, authenticated;
revoke all on table public.challenges from anon, authenticated;
revoke all on table public.habits from anon, authenticated;
revoke all on table public.habit_entries from anon, authenticated;
revoke all on table public.ai_conversations from anon, authenticated;
revoke all on table public.password_reset_tokens from anon, authenticated;
