create table if not exists public.projects (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    title text not null check (char_length(btrim(title)) between 1 and 200),
    description text check (description is null or char_length(description) <= 2000),
    category text not null check (char_length(btrim(category)) between 1 and 100),
    status text not null default 'in_progress'
        check (status in ('in_progress', 'under_review', 'complete')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists ix_projects_user_id on public.projects (user_id);
create index if not exists ix_projects_user_status on public.projects (user_id, status);

create table if not exists public.project_categories (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    name text not null check (char_length(btrim(name)) between 1 and 100),
    normalized_name text not null check (char_length(btrim(normalized_name)) between 1 and 100),
    created_at timestamptz not null default now(),
    constraint uq_project_categories_user_normalized_name unique (user_id, normalized_name)
);

create index if not exists ix_project_categories_user_id on public.project_categories (user_id);

-- FastAPI uses a trusted direct Postgres connection and performs ownership checks.
-- Keep these tables unavailable through Supabase's browser-facing API roles.
revoke all on table public.projects, public.project_categories from public, anon, authenticated;
revoke all on sequence public.projects_id_seq, public.project_categories_id_seq from public, anon, authenticated;
